# Copied and modified from k0sctl: https://github.com/k0sproject/k0sctl/blob/main/.github/workflows/release.yaml

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clear workflow caches
        uses: easimon/wipe-cache@main

      # Ugly hack to get the tag name
      # github.ref gives the full reference like refs.tags.v0.0.1-beta1
      - name: Branch name
        id: branch_name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}

      - name: Unshallow git history
        env:
          TAG_NAME: ${{ steps.branch_name.outputs.TAG_NAME }}
        run: |
          git fetch --unshallow
          git checkout ${TAG_NAME}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build binaries
        run: ./scripts/build.sh

      - name: Generate changelog
        run: ./scripts/changelog.sh

      - name: Create release and upload binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/*
          body_path: bin/changelog.md
          tag_name: ${{ steps.branch_name.outputs.TAG_NAME }}
          name: ${{ steps.branch_name.outputs.TAG_NAME }}
          draft: true # So we can manually edit before publishing
          prerelease: ${{ contains(steps.branch_name.outputs.TAG_NAME, '-') }} # v0.1.2-beta1, 1.2.3-rc1
